variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - build

test:Docker:
  image: mcr.microsoft.com/powershell:latest
  stage: test
  tags:
    - Docker
  artifacts:
    untracked: true
    expire_in: 1 week
    when: always
  script:
    - pwsh Execute-Tests.ps1

build:Docker:
  stage: build
  tags:
    - Psv5
  script:
    - mkdir TestResult
    - copy *.xml TestResult
  dependencies:
    - test:Docker
  artifacts:
    reports:
      junit: TestResult/*.xml

    expire_in: 1 week
    when: always
